{
 "title": "NATS Streaming Proxy",
 "time": { "from": "now-3h", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   {
    "name": "instance",
    "query": "label_values(nats_streaming_proxy_uptime, instance)"
   }
  ]
 },
 "panels": [
  {
   "title": "requests",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (subject) (irate(nats_streaming_proxy_requests_total{job=\"nats-streaming-proxy\", instance=\"$instance\"}[1m]))",
     "legendFormat": "{{subject}}"
    },
    {
     "expr": "sum by (subject) (irate(nats_streaming_proxy_failed_requests_total{job=\"nats-streaming-proxy\", instance=\"$instance\"}[1m]))",
     "legendFormat": "failed {{subject}}"
    }
   ]
  },
  {
   "title": "connections",
   "type": "graph",
   "gridPos": { "h": 8, "w": 8, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum by (address) (nats_streaming_proxy_current_connections{job=\"nats-streaming-proxy\", instance=\"$instance\"})",
     "legendFormat": "{{address}}"
    }
   ]
  },
  {
   "title": "uptime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 20, "y": 0 },
   "format": "s",
   "valueName": "current",
   "targets": [
    {
     "expr": "nats_streaming_proxy_uptime{instance=\"$instance\"}"
    }
   ]
  },
  {
   "title": "total connections",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 4 },
   "format": "short",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(nats_streaming_proxy_total_connections{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "current connections",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 6 },
   "format": "none",
   "valueName": "current",
   "targets": [
    {
     "expr": "sum(nats_streaming_proxy_current_connections{instance=\"$instance\"})"
    }
   ]
  },
  {
   "title": "process memory",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "process_resident_memory_bytes{job=\"nats-streaming-proxy\", instance=\"$instance\"}",
     "legendFormat": "resident"
    },
    {
     "expr": "process_virtual_memory_bytes{job=\"nats-streaming-proxy\", instance=\"$instance\"}",
     "legendFormat": "virtual"
    }
   ]
  },
  {
   "title": "go memstats",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 8 },
   "yaxes": [
    { "format": "bytes" }
   ],
   "targets": [
    {
     "expr": "go_memstats_alloc_bytes{job=\"nats-streaming-proxy\", instance=\"$instance\"}",
     "legendFormat": "bytes allocated"
    },
    {
     "expr": "rate(go_memstats_alloc_bytes_total{job=\"nats-streaming-proxy\", instance=\"$instance\"}[30s])",
     "legendFormat": "alloc rate"
    },
    {
     "expr": "go_memstats_stack_inuse_bytes{job=\"nats-streaming-proxy\", instance=\"$instance\"}",
     "legendFormat": "stack inuse"
    },
    {
     "expr": "go_memstats_heap_inuse_bytes{job=\"nats-streaming-proxy\", instance=\"$instance\"}",
     "legendFormat": "heap inuse"
    }
   ]
  },
  {
   "title": "goroutines",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "go_goroutines{job=\"nats-streaming-proxy\", instance=\"$instance\"}",
     "legendFormat": "gorutines"
    }
   ]
  },
  {
   "title": "GC duration quantiles",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 15 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "expr": "go_gc_duration_seconds{job=\"nats-streaming-proxy\", instance=\"$instance\"}",
     "legendFormat": " {{quantile}}"
    }
   ]
  }
 ]
}